### ISSUE TITLE
How to use the user-bundle after 3.0

### ISSUE THREAD

**Issue by RomainSanchez** [sonata-project/SonataUserBundle#728] opened 2016-05-11 15:27 UTC
The user bundle requires sonata admin 2.2.9 but the doctrineormadmin bundle requires sonata admin 3.0.How am i supposed to get around this?i already have to use aliases on admin and doctrine to make them appear as 2.4.I am completely lost in all the dependency problems 3.0 created.Why evolve to 3.0 for the core bundles before getting all the other bundles ready?(already read #3731 comments).

**Comment by Soullivaneuh** [comment] 2016-05-12 18:59
> Why evolve to 3.0 for the core bundles before getting all the other bundles ready?

Please note, and note again, that we are modifying versionning from **unstable** branches.

Using unstable branch is at your own risks.

For the moment, user-bundle is not officially ready for admin-bundle 3.0. If you want to force it, you can use composer branch aliasing: https://getcomposer.org/doc/articles/aliases.md#require-inline-alias

Otherwise, you can stay at admin-bundle 2.3 that is compatible with user-bundle 2.2.

**Comment by Soullivaneuh** [comment] 2016-05-12 19:57
See also https://github.com/sonata-project/SonataUserBundle/issues/730.

**Comment by RomainSanchez** [comment] 2016-05-13 10:18
thanks for the quick reply

**Comment by Soullivaneuh** [comment] 2016-05-13 17:55
You can now use 3.x-dev branch of user-bundle to have compatibility with admin-bundle 3.0.

**Comment by Galaxias** [comment] 2016-05-13 18:26
Hi @Soullivaneuh ! How am i supposed to use the 3.x-dev branch? Composer does not find it.

**Comment by Soullivaneuh** [comment] 2016-05-13 19:02
Erf, packagist failed to update: https://packagist.org/packages/sonata-project/user-bundle

@rande Could you please take a look?

BTW, it would be better to register it as a service instead of a webhooks url.

**Comment by Soullivaneuh** [comment] 2016-05-14 20:30
@Galaxias We actually have an issue with Packagist for some Sonata packages: https://github.com/composer/packagist/issues/674

Sadly, this one is part of them. :-/

**Comment by Galaxias** [comment] 2016-05-14 21:11
@Soullivaneuh That's sad. I hope this will be fixed soon!

**Comment by cmroanirgo** [comment] 2016-05-16 10:09
I'm not meaning to push any buttons: clearly you guys are working hard. 
Should I assume the purpose of installing sonata admin 3.0 is because of symfony 3.0? If so, then the following error is prudent when adding sonata user bundle 3.x-dev:
```
Problem 1
    - Conclusion: remove symfony/symfony v3.0.6
    ... [snip many lines]
    - don't install symfony/form v2.8.6|don't install symfony/symfony v3.0.0
```

This is after using branch aliasing (as suggested above). This is what I've put in my composer.json:
```
"repositories": [
        {
            "type": "git",
            "url": "https://github.com/sonata-project/SonataUserBundle.git"
        }
    ],
"require": {
    "symfony/symfony": "3.0.*",
    ...
   "sonata-project/user-bundle": "3.x-dev"
    },
```
Conclusion: we must be patient a bit longer, even if the packagist problem is repaired... unless I've made a typo somewhere in my composer.json?

**Comment by sagikazarmark** [comment] 2016-05-19 22:46
> If so, then the following error is prudent when adding sonata user bundle 3.x-dev:

This is caused by FOS User Bundle: 1.x does not support Symfony 3.0

**Comment by Soullivaneuh** [comment] 2016-05-19 22:48
> Should I assume the purpose of installing sonata admin 3.0 is because of symfony 3.0? If so, then the 

Absolutely not. Sonata versioning is not following SF one anymore, this was a mistake.

User-bundle is still not compatible with SF 3.0 essantially because of FOSUserBundle 1 as @sagikazarmark said.

BTW, 3.0.0 is out right now so I'm closing this issue.

**Closed by Soullivaneuh** 2016-05-19 22:48 UTC

**Comment by greg0ire** [comment] 2016-07-21 15:58
Good new here : https://github.com/FriendsOfSymfony/FOSUserBundle/pull/2167#issuecomment-232025427
