### ISSUE TITLE
logout and profile disappear

### ISSUE THREAD

**Issue by paolocl** [sonata-project/SonataUserBundle#820] opened 2016-12-28 21:13 UTC
SONATA USER BUNDLE  ^3.2
SYNFONY 2.8

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.10.3 The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/classification-bundle     3.1.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.1.2  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.4  Symfony SonataIntlBundle
sonata-project/media-bundle              3.3.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0  Symfony SonataNotificationBundle
sonata-project/user-bundle               3.2.0  Symfony SonataUserBundle

```

#### Symfony packages

```bash
$ composer show symfony/*
sonata-project/admin-bundle              3.10.3 The missing Symfony Admin Generator
sonata-project/block-bundle              3.2.0  Symfony SonataBlockBundle
sonata-project/cache                     1.0.7  Cache library
sonata-project/classification-bundle     3.1.0  Symfony SonataClassificationBundle
sonata-project/core-bundle               3.1.2  Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2    Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2  Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.2  Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.1.10 Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.0  Lightweight Exporter library
sonata-project/google-authenticator      1.0.2  Library to integrate Google Authenticator into a PHP project
sonata-project/intl-bundle               2.2.4  Symfony SonataIntlBundle
sonata-project/media-bundle              3.3.0  Symfony SonataMediaBundle
sonata-project/notification-bundle       3.0.0  Symfony SonataNotificationBundle
sonata-project/user-bundle               3.2.0  Symfony SonataUserBundle
MBP-de-Paolo:BS paolocastro$  composer show symfony/*
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/finder             v3.2.1  Symfony Finder Component
symfony/intl               v3.2.1  A PHP replacement layer for the C intl extension that includes additional data from the ICU library.
symfony/monolog-bundle     2.11.3  Symfony MonologBundle
symfony/phpunit-bridge     v2.8.15 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0  Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php54     v1.3.0  Symfony polyfill backporting some PHP 5.4+ features to lower PHP versions
symfony/polyfill-php55     v1.3.0  Symfony polyfill backporting some PHP 5.5+ features to lower PHP versions
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.4.2  Symfony SwiftmailerBundle
symfony/symfony            v2.8.15 The Symfony PHP framework
```

#### PHP version

```bash
$ php -v
PHP 5.5.32
```

## Subject

The logout button and profile button in the top right disspeared

<img width="375" alt="capture d ecran 2016-12-28 a 22 09 51" src="https://cloud.githubusercontent.com/assets/10263629/21531707/805cdc8c-cd4a-11e6-9ca0-bd97134f4820.png">

My block is (I have only one) 
```bash
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.user.block.menu:
        sonata.user.block.account:
        sonata.block.service.text:
        sonata.admin.block.admin_list:
            contexts: [user]
        sonata.block.service.notification:
        sonata.block.service.rss:
```

I don't know Why and when it desepeard

I don't have extend the Stnadard layout

Can you help me?
Thx

**Comment by core23** [comment] 2016-12-29 10:21
Sure this is a user Bundle problem. Where would you expect this lagout button?

**Comment by paolocl** [comment] 2016-12-29 22:02
in the right top corner

**Comment by core23** [comment] 2016-12-30 04:54
Please leave a little more information... WHERE in the right top corner of? Your mail app? Which page? Which template?

Are you talking about the user bundle or the admin bundle?

**Comment by paolocl** [comment] 2017-01-04 20:41
It's on every page, in the standard layout template i think.
I think it's with the Sonata Core but it's appear after installing sonataUser normally.

Normaly there is this 
<img width="284" alt="capture d ecran 2017-01-04 a 21 38 45" src="https://cloud.githubusercontent.com/assets/10263629/21658293/409965da-d2c6-11e6-9ac4-b5e808af3243.png">

**Comment by core23** [comment] 2017-01-04 21:09
The screen is from the admin backend. Can you just spend a little more time in an analysis and supply more information. We can't help you with that lack of information.

**Comment by core23** [comment] 2017-01-05 15:41
Closing this for now, because it looks like a implementation problem. Please ask general questions on stackoverflow until this is a real issue.

**Closed by core23** 2017-01-05 15:41 UTC

**Comment by Ehmz** [comment] 2018-02-20 02:27
<img width="1152" alt="screen shot 2018-02-20 at 10 25 17 am" src="https://user-images.githubusercontent.com/26210483/36404887-65150cb0-1628-11e8-9678-aa2ef36777e4.png">
I have same problem. i have set up this for several time with different from scratch projects but still it didn't show up the dropdown button for profile and logout.  So i dont think so the problem is on it's implementation or setting up the admin bundle.

**Comment by pa-** [comment] 2018-05-15 09:45
@Ehmz Looks like you are not logged in ("anon." in the Debug Toolbar). Your User also must have/inherit the `ROLE_SONATA_ADMIN` Role

**Comment by malutanpetronel** [comment] 2019-02-09 11:11
I did upgraded from 2.3 to 3 and the current configs I had are working with the specification that the top menu for logout is not shown anymore... No changed template in my case. 
...
   "sonata-project/core-bundle": "^3.1",
        "sonata-project/admin-bundle": "^3",
        "sonata-project/doctrine-orm-admin-bundle": "^3",
        "sonata-project/block-bundle": "^3",


        "doctrine/migrations": "1.*",
        "doctrine/doctrine-migrations-bundle": "dev-master",

        "sonata-project/easy-extends-bundle": "^2.2",
        "sonata-project/user-bundle": "^3.0",
        "friendsofsymfony/user-bundle": "^1.3",
        "sonata-project/datagrid-bundle": "~2.2@dev",

...

these are my blocks

sonata_block:
    # https://github.com/sonata-project/sandbox/blob/2.4-develop/app/config/sonata/sonata_block.yml#L16-L17
    default_contexts: [cms]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        # Your other blocks
        sonata.admin.block.search_result:
            contexts: [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

        sonata.user.block.menu:    # used to display the menu in profile pages
        sonata.user.block.account: # used to display menu option (login option)
        sonata.block.service.text: # used to if you plan to use Sonata user routes

What do I miss here please ?
