### ISSUE TITLE
Change User Avatar

### ISSUE THREAD

**Issue by maavia10** [sonata-project/SonataUserBundle#943] opened 2017-11-06 13:26 UTC
I am using Sonata User Bundle In the upper right corner there is a menu with a logout button and the user's avatar. What I can't find is how to access to user's profile to change among other things, the avatar and his password.

**Comment by Hanmac** [comment] 2017-11-06 14:01
@maavia10 the avatar currently can't be changed with the default install

there are bundles/modules planned using gravatar #529, 
Someone recommented https://github.com/henrikbjorn/GravatarBundle, but there is no connection with Sonata as far as i know.

**Comment by Soullivaneuh** [comment] 2017-11-06 14:25
Duplicate of #529

**Closed by Soullivaneuh** 2017-11-06 14:25 UTC
