### ISSUE TITLE
PHP ^7.0 and Symfony ^3.0

### ISSUE THREAD

**Issue by Gastmeier** [sonata-project/SonataUserBundle#936] opened 2017-10-30 10:51 UTC
PHP version 7.1 is already too high for our requirements. All the other bundles go along with that. This one is not and it hinders the desire to upgrade to Symfony ^3.0.

So far, Symfony <3.4 has `"php": "^5.5.9|>=7.0.8"`. These versions become unaccessible if you have a constraint that says PHP <7.1.

Thats why the question: PHP ^7.0 and Symfony ^3.0, can you make it happen?

**Comment by greg0ire** [comment] 2017-10-30 10:52
@Gastmeier we recently reverted all our bundles to `^5.6 || ^7.0`, but did not communicate about that yet.

**Comment by Gastmeier** [comment] 2017-10-30 10:55
which version to use? `"sonata-project/user-bundle": "^3.0"` does not to the trick.

**Comment by Soullivaneuh** [comment] 2017-10-30 10:59
> which version to use? `"sonata-project/user-bundle": "^3.0"` does not to the trick.

It should, and should install this: https://packagist.org/packages/sonata-project/user-bundle#3.3.0

3.4.0 is PHP 7.1 only but 3.5.0 will have the PHP 5.6 support back.

> So far, Symfony <3.4 has `"php": "^5.5.9|>=7.0.8"`

It's a Symfony choice, not our. We reverted to PHP 5.6 after a second vote, indeed. But it's still a choice.

Please also note: The next major version will be PHP 7.1 only and the older branches will be not maintained, except for critical bugfixes.

Regards.

**Comment by Gastmeier** [comment] 2017-10-30 11:02
> It should, and should install this: https://packagist.org/packages/sonata-project/user-bundle#3.3.0

3.3 uses `"php": "^5.3 || ^7.0"` but it needs Symfony ^2.3 (through `"symfony/security": "^2.3"`)

> 3.4.0 is PHP 7.1 only but 3.5.0 will have the PHP 5.6 support back.

So i need to wait for 3.5.0. When will it arrive? Any estimation about that?

**Comment by Gastmeier** [comment] 2017-10-30 11:26
I just realized that you would have to upgrade to `"friendsofsymfony/user-bundle": "^2.0"`.

@greg0ire You closed this issue too soon. It is not only about the PHP version, its about the PHP version in conjunction with the Symfony version.

Thus my question remains. When will there be an upgrade to Symfony ^3.0 and will it be in conjunction with PHP ^7.0? Or will you jump to PHP version ^7.1?

**Comment by greg0ire** [comment] 2017-10-30 11:31
Oh indeed, I misunderstood the issue.

**Comment by Soullivaneuh** [comment] 2017-10-30 11:52
@sonata-project/contributors Do we still have a reason to not support SF 3 on current stable?

**Comment by Soullivaneuh** [comment] 2017-10-30 16:59
@Gastmeier Unfortunately, we can't provide Symfony 3 support because of the current FOSUser v1 support of the stable branch.

@sonata-project/contributors Two possible options:

- Drop FOSUser v1 support on the current stable, because maintaining both plus Symfony v3 looks quite impossible. We can do this according to semver and our new policy.
- Just wait and release the next major. But it will be PHP 7.1 only.

I let the main maintainers choose what is the best.

**Comment by quaertym** [comment] 2017-11-02 18:07
I am interested in this too. When can we expect a version with PHP ^7.0 Symfony ^3.0 and FOSUser ^2.0?

**Comment by Soullivaneuh** [comment] 2017-11-06 21:17
After discussion with the team, here is the issue: We are stuck with FOSUser v1 (and SF 2.8) on stable, so the only way is to go to master.

Unfortunately, the next major release will be PHP 7.1 only.

Closing as wontfix for this subject.

**Closed by Soullivaneuh** 2017-11-06 21:17 UTC

**Comment by sev-signal** [comment] 2017-11-07 08:57
@Soullivaneuh 
Ok, can we have an idea of the roadmap? When is gonna be this next release?
Thx

**Comment by Soullivaneuh** [comment] 2017-11-07 08:58
@sev-signal We don't have precise roadmap.

I just can ensure you it will at least at December, if the master branch is ready,

**Comment by sev-signal** [comment] 2017-11-07 08:59
OK, so by the end of the year. Thanks

**Comment by lukepass** [comment] 2018-02-22 16:43
Hello, is there a solution for this?
I have a constraint of PHP 7.0.25 and I can't upgrade to Symfony 3.4 because SonataUserBundle requires PHP 7.1.

Thanks.

**Comment by greg0ire** [comment] 2018-02-22 16:51
@jordisala1991 has a fork he maintains.

**Comment by lukepass** [comment] 2018-02-22 16:53
So the official SonataUserBundle fork isn't going to provide a PHP 7.0 compatible version?
If you can confirm this I think it's time to force my customer to upgrade to a new PHP version :)

**Comment by greg0ire** [comment] 2018-02-22 16:55
I can confirm this :)

**Comment by lukepass** [comment] 2018-02-22 16:58
Ok, thank you! :)
