### ISSUE TITLE
intl-bundle 2.3.0 conflicts with sonata-project/user-bundle dev-master

### ISSUE THREAD

**Issue by Filoz** [sonata-project/SonataUserBundle#879] opened 2017-05-18 08:51 UTC
#### Sonata packages

```bash
$ composer show sonata-project/*
sonata-project/admin-bundle              3.18.2             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/classification-bundle     3.3.0              Symfony SonataClassificationBundle
sonata-project/core-bundle               3.4.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              Lightweight Exporter library
sonata-project/formatter-bundle          3.2.0              Symfony SonataFormatterBundle
sonata-project/media-bundle              3.5.1              Symfony SonataMediaBundle
sonata-project/notification-bundle       3.1.0              Symfony SonataNotificationBundle
sonata-project/seo-bundle                2.x-dev 43c4437    Symfony SonataSeoBundle
sonata-project/user-bundle               dev-master 34a771f Symfony SonataUserBundle

```

#### Symfony packages

```bash
$ composer show symfony/*
symfony/assetic-bundle     v2.8.1  Integrates Assetic into Symfony2
symfony/monolog-bundle     v2.12.1 Symfony MonologBundle
symfony/phpunit-bridge     v3.2.8  Symfony PHPUnit Bridge
symfony/polyfill-intl-icu  v1.3.0  Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0  Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0  Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0  Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0  Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0  Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.5.4  Symfony SwiftmailerBundle
symfony/symfony            v3.2.8  The Symfony PHP framework

```

#### PHP version

```bash
$ php -v
PHP 7.0.15 (cli) (built: Jan 17 2017 13:58:38) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies

```

## Subject
I use   `"sonata-project/user-bundle": "dev-master"` because of I'm using `"friendsofsymfony/user-bundle": "~2.0"`

but when I run `composer update` I get the following error

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sonata-project/intl-bundle 2.3.0 conflicts with sonata-project/user-bundle[dev-master].
    - sonata-project/intl-bundle 2.3.0 conflicts with sonata-project/user-bundle[dev-master].
    - Installation request for sonata-project/intl-bundle ^2.3 -> satisfiable by sonata-project/intl-bundle[2.3.0].
    - Installation request for sonata-project/user-bundle dev-master -> satisfiable by sonata-project/user-bundle[dev-master].

```

**Comment by Filoz** [comment] 2017-05-18 09:01
the "problem" is in sonata intl

https://github.com/sonata-project/SonataIntlBundle/blob/master/composer.json#L37

**Comment by greg0ire** [comment] 2017-05-20 14:32
See https://github.com/sonata-project/SonataIntlBundle/pull/114
@Soullivaneuh, any comments on this?

**Comment by psyray** [comment] 2017-06-04 10:48
Same problem for me. I think this "bug" could be marked as **confirmed** :)
2.0 FOSUserBundle is necessary because of Symfony 3.2 usage.

Here's my config.
```
sonata-project/admin-bundle              3.18.2             The missing Symfony Admin Generator
sonata-project/block-bundle              3.3.2              Symfony SonataBlockBundle
sonata-project/cache                     1.0.7              Cache library
sonata-project/core-bundle               3.4.0              Symfony SonataCoreBundle
sonata-project/datagrid-bundle           2.2.1              Symfony SonataDatagridBundle
sonata-project/doctrine-extensions       1.0.2              Doctrine2 behavioral extensions
sonata-project/doctrine-orm-admin-bundle 3.1.4              Symfony Sonata / Integrate Doctrine ORM into the SonataAdminBundle
sonata-project/easy-extends-bundle       2.2.0              Symfony SonataEasyExtendsBundle
sonata-project/exporter                  1.7.1              Lightweight Exporter library
sonata-project/formatter-bundle          3.2.1              Symfony SonataFormatterBundle
sonata-project/user-bundle               dev-master 8cbee5f Symfony SonataUserBundle
```
```
symfony/assetic-bundle     v2.8.1 Integrates Assetic into Symfony2
symfony/monolog-bundle     v3.1.0 Symfony MonologBundle
symfony/phpunit-bridge     v3.3.0 Symfony PHPUnit Bridge
symfony/polyfill-apcu      v1.3.0 Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-intl-icu  v1.3.0 Symfony polyfill for intl's ICU-related data and classes
symfony/polyfill-mbstring  v1.3.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php56     v1.3.0 Symfony polyfill backporting some PHP 5.6+ features to lower PHP versions
symfony/polyfill-php70     v1.3.0 Symfony polyfill backporting some PHP 7.0+ features to lower PHP versions
symfony/polyfill-util      v1.3.0 Symfony utilities for portability of PHP codes
symfony/security-acl       v3.0.0 Symfony Security Component - ACL (Access Control List)
symfony/swiftmailer-bundle v2.6.2 Symfony SwiftmailerBundle
symfony/symfony            v3.2.9 The Symfony PHP framework
```

```
PHP 7.1.1 (cli) (built: Feb  1 2017 01:39:46) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans
    with Zend OPcache v7.1.1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by jxamorro** [comment] 2017-10-02 18:05
What is necesary to resolve this problem?

**Comment by wissemwis** [comment] 2017-10-13 10:26
The source of this conflict is the non existence of a release 4.x of SonataUserBundle
To resolve this problem we need to have a 4.x release of SonataUserBundle
Please is there a release planified ?

**Comment by greg0ire** [comment] 2017-10-13 10:53
Yes

**Comment by jxamorro** [comment] 2017-10-31 12:44
Do you know approximate date for the release?
thanks

**Comment by greg0ire** [comment] 2017-10-31 12:47
Probably late 2017

**Comment by jxamorro** [comment] 2017-10-31 15:22
thanks @greg0ire

**Comment by bartosz-malec** [comment] 2017-12-08 08:25
I have chacked that SonataUserBundle 4.0 works fine with SonataIntlBundle 2.4, so this task should be closed.

**Comment by OskarStark** [comment] 2017-12-08 08:27
Thank you for the feedback 👍

**Closed by OskarStark** 2017-12-08 08:27 UTC
Labels: bug, unconfirmed
