### ISSUE TITLE
Can't install Bundle

### ISSUE THREAD

**Issue by marvoh** [sonata-project/SonataUserBundle#723] opened 2016-04-26 15:18 UTC
Hi,

I've been unable to install this on either Symfony3 or 2.8.x the whole afternoon because I am experiencing an error I have never encountered before

here is the error 

     `Your requirements could not be resolved to an installable set of packages.

      Problem 1
        - sonata-project/user-bundle 2.2.4 requires sonata-project/doctrine-extensions ~1.0 -> satisfiable by sonata-project/doctrine-extensions[1.0.0, 1.0.1, 1.0.2] but these conflict with your requirements or minimum-stability
        - sonata-project/user-bundle 2.2.3 requires sonata-project/doctrine-extensions ~1.0 -> satisfiable by sonata-project/doctrine-extensions[1.0.0, 1.0.1, 1.0.2] but these conflict with your requirements or minimum-stability
        - sonata-project/user-bundle 2.2.2 requires sonata-project/doctrine-extensions ~1.0 -> satisfiable by sonata-project/doctrine-extensions[1.0.0, 1.0.1, 1.0.2] but these conflict with your requirements or minimum-stability
        - sonata-project/user-bundle 2.2.1 requires sonata-project/doctrine-extensions ~1.0 -> satisfiable by sonata-project/doctrine-extensions[1.0.0, 1.0.1, 1.0.2] but these conflict with your requirements or minimum-stability
        - sonata-project/user-bundle 2.2.0 requires sonata-project/doctrine-extensions ~1.0 -> satisfiable by sonata-project/doctrine-extensions[1.0.0, 1.0.1, 1.0.2] but these conflict with your requirements or minimum-stability
        - Installation request for sonata-project/user-bundle ^2.2 -> satisfiable by sonata-project/user-bundle[2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4].`

Here's my composer:

    `"require": {
        "php": ">=5.5.9",
        "symfony/symfony": "~2.8",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3",
        "symfony/monolog-bundle": "^2.8",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "friendsofsymfony/user-bundle": "~1.3",
        "sonata-project/admin-bundle": "dev-master",
        "sonata-project/doctrine-orm-admin-bundle": "dev-master",
        "sonata-project/easy-extends-bundle": "^2.1",
        "sonata-project/doctrine-extensions": "dev-master",
        "sonata-project/user-bundle": "^2.2"
    }`

I'm I missing something?

**Comment by greg0ire** [comment] 2016-04-26 15:21
Yes : you are asking for a version of doctrine-extensions (why?) and the user bundle is asking for another.

**Comment by marvoh** [comment] 2016-04-26 15:23
Sorry forgot that line there in while trying to fix issue on Symfony 3. Let me remove and see if there's a difference

**Comment by marvoh** [comment] 2016-04-26 15:28
Same error

**Comment by greg0ire** [comment] 2016-04-26 15:29
**Same** error ? What does composer why-not 'sonata-project/user-bundle:^2.2' show ?

**Comment by marvoh** [comment] 2016-04-26 15:44
Could not find package "'sonata-project/user-bundle" in your project

**Comment by greg0ire** [comment] 2016-04-26 15:45
> Could not find package "'sonata-project/user-bundle" in your project

Sorry, the command I gave you is not relevant when installing, only when updating. Is the error you get really exactly the same?

**Comment by greg0ire** [comment] 2016-04-26 15:48
Can you try this : `composer depends sonata-project/doctrine-extensions` ? You should get the list of packages that require this package (possibly with other constraints).

**Comment by marvoh** [comment] 2016-04-26 15:56
Thanks for taking your time to help. I get the message below. 

    There is no installed package depending on "sonata-project/doctrine-extensions"

**Comment by greg0ire** [comment] 2016-04-26 15:57
What if you try requiring doctrine-extensions ? `composer require sonata-project/doctrine-extensions ~1.0`

**Comment by marvoh** [comment] 2016-04-26 16:03
This is what I get, 

     Problem 1
    - sonata-project/user-bundle 2.2.0 requires sonata-project/admin-bundle ~2.2.7 -> satisfiable by sonata-project/admin-bundle[2.2.x-dev].
    - sonata-project/user-bundle 2.2.1 requires sonata-project/admin-bundle ~2.2.7 -> satisfiable by sonata-project/admin-bundle[2.2.x-dev].
    - sonata-project/user-bundle 2.2.2 requires sonata-project/admin-bundle ~2.2.7 -> satisfiable by sonata-project/admin-bundle[2.2.x-dev].
    - sonata-project/admin-bundle 2.2.x-dev requires sensio/generator-bundle ~2.2,<2.5 -> satisfiable by sensio/generator-bundle[2.2.x-dev, 2.4.x-dev, v2.2.0, v2.2.0-BETA1, v2.2.0-BETA2, v2.2.0-RC1, v2.2.0-RC2, v2.2.0-RC3, v2.2.1, v2.2.2, v2.2.3, v2.2.4, v2.2.5, v2.2.6, v2.3.0, v2.3.0-BETA1, v2.3.0-BETA2, v2.3.0-RC1, v2.3.1, v2.3.2, v2.3.3, v2.3.4, v2.3.5, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.4.4, v2.4.5] but these conflict with your requirements or minimum-stability
    - sonata-project/user-bundle 2.2.4 requires sonata-project/admin-bundle ~2.2,>=2.2.9 -> satisfiable by sonata-project/admin-bundle[2.2.x-dev, 2.3.x-dev].
    - sonata-project/user-bundle 2.2.3 requires sonata-project/admin-bundle ~2.2,>=2.2.9 -> satisfiable by sonata-project/admin-bundle[2.2.x-dev, 2.3.x-dev].
    - Conclusion: don't install sonata-project/admin-bundle 2.3.x-dev
    - Installation request for sonata-project/user-bundle ^2.2 -> satisfiable by sonata-project/user-bundle[2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4].

T

**Comment by greg0ire** [comment] 2016-04-26 16:06
the admin bundle dev master can't be installed along with user-bundle ^2.2 I guess you should user bundle dev master too…

**Comment by greg0ire** [comment] 2016-04-26 16:07
Hum sorry that won't work either.

**Comment by marvoh** [comment] 2016-04-26 16:08
Yeah, tried it to no effect. What could be the issue?

**Comment by greg0ire** [comment] 2016-04-26 16:08
See #722

**Comment by greg0ire** [comment] 2016-04-26 16:09
Also, see #721 . You did not do your research, it seems.

**Comment by greg0ire** [comment] 2016-04-26 16:09
Closing as duplicate of #721

**Closed by greg0ire** 2016-04-26 16:09 UTC

**Comment by marvoh** [comment] 2016-04-26 16:11
Sorry about that. I googled before posting here. Thanks for taking your time

**Comment by greg0ire** [comment] 2016-04-26 16:12
No problem, next time please also look at the issues ;)
